### ISSUE TITLE
Seems to crash and cause spam loop

### ISSUE THREAD

**Issue by Trnrr** [origami-games/quazi-modded#1]
If I add this and join my world I get crash loops

Error before spam: https://gist.github.com/Trnrr/f90c376aeee9d5975f677549563a0a3d
Another : https://gist.github.com/Trnrr/516cad0ded35ab1a29f15681315b7888
Eventually just spams this: https://gist.github.com/Trnrr/29565880d61c5488ad5ee90100c7426c

If I remove the mod is doesn't do this. Just putting this here since I thought it was that mod first https://github.com/haykam821/Lootstrap/issues/1

**Comment by dvitski** [comment]
It looks like an issue with multiple mods clashing from what I can see; I'll take a further look into it later today

**Comment by dvitski** [comment]
Could you put [this pack](https://github.com/origami-games/quazi-modded/files/4151958/Recipe.Unlock.Removal.Test.zip) in your world's `datapacks` folder, with Quazi-Modded enabled, and see if the issue is fixed? If so, I know it's with the recipe giving

**Comment by dvitski** [comment]
This is a vanilla bug, due to the fact that too many recipes given at the same time causes the game to crash. This is due to the fact that the duration that the recipe toast is visible for is the same each time, so the game has to calculate how long each new recipe displays for in the visual cycle; too many recipes results in a divided `0` somewhere in the maths, and so the game crashes

[Fabric Discord:](https://discordapp.com/channels/507304429255393322/507982478276034570/674259028527939594)
![image](https://user-images.githubusercontent.com/36608902/73867280-50dc2b80-483e-11ea-9316-ad135bce0f61.png)

**Comment by dvitski** [comment]
As a side note, I'm planning on removing this feature anyways, as it's not really that useful.
